# Generated by Django 5.0.6 on 2024-05-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_imageapi_id_alter_imageapi_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAPI',
        ),
    ]
