# Generated by Django 5.0.6 on 2024-05-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_imagefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
