# Generated by Django 5.0.6 on 2024-05-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
