# Generated by Django 5.0.4 on 2024-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_filter_recipes_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="user",
        ),
        migrations.AddField(
            model_name="recipes",
            name="category",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
