# Generated by Django 5.0.4 on 2024-05-14 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_filter_recipes_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="user",
        ),
    ]
