# Generated by Django 5.0.4 on 2024-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_recipes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="category",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
