# Generated by Django 5.0.6 on 2024-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_category'),
    ]

    operations = []
