# Generated by Django 5.0.6 on 2024-05-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_imageapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageapi',
            name='id',
        ),
        migrations.AlterField(
            model_name='imageapi',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
