# Generated by Django 5.0.6 on 2024-05-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_imageapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='dishid',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
