# Generated by Django 5.0.6 on 2024-05-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_delete_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.recipes')),
                ('image', models.ImageField(upload_to='recipe_images/')),
            ],
        ),
    ]
