# Generated by Django 5.0.6 on 2024-05-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipes_user_recipes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
