# Generated by Django 5.0.6 on 2024-05-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='dishid',
            field=models.IntegerField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
